apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - clusterrolebinding.yml
  - deployment.yml
  - serviceaccount.yml
  - service.yml
configMapGenerator:
  - name: traefik-conf
    files:
      - traefik.toml
