language: C
sudo: false
before_install:
  - wget https://github.com/instrumenta/kubeval/releases/download/0.14.0/kubeval-linux-amd64.tar.gz
  - tar xzvf kubeval-linux-amd64.tar.gz
  - chmod u+x kubeval
script:
  - find . -name "*.yaml" -o -name "*.yml" | grep -v -E ".travis.yml|kustomizeconfig" | while read line; do ./kubeval --strict  --ignore-missing-schemas -o tap $line; done
