apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: external-dns
spec:
  template:
    spec:
      containers:
      - name: external-dns
        args:
          - --provider=rfc2136
          - --rfc2136-host=123.123.123.123
          - --rfc2136-port=53
          - --rfc2136-zone=your-domain.com
          - --rfc2136-tsig-secret=$(RFC2136_TSIG_SECRET)
          - --rfc2136-tsig-secret-alg=hmac-sha256
          - --rfc2136-tsig-keyname=$(RFC2136_TSIG_KEYNAME)
          - --rfc2136-tsig-axfr
        env:
        - name: RFC2136_TSIG_SECRET
          valueFrom:
            secretKeyRef:
              name: external-dns
              key: rfc2136_tsig_secret
        - name: RFC2136_TSIG_KEYNAME
          valueFrom:
            secretKeyRef:
              name: external-dns
              key: rfc2136_tsig_keyname
