apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../base
  - ../../../postgres/base
vars:
- name: POSTGRES_SERVICE
  objref:
    kind: Service
    name: postgres
    apiVersion: v1

