apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - crd.yml
  - rolebinding.yml
  - clusterrolebinding.yml
  - configmap.yml
  - service.yml
  - deployment.yml
  - serviceaccount.yml
  - secret.yml
